In [2]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

### testing data example:
dump:
48435720524	4295889557	3011624	SPG	1	48433350304	1	1000190358	1	1000190363	1.00976E+12	HalfYear	3011647	500111	0	ORG	3013560		3019679	INC	3011683	36	14	ESPARS	3012178	SS	1000716240	D	3013563			BEPSBC	3014780					1	97	Diluido	505074	Reported Basic EPS	505205			0.29029	0.30711	Reported Basic EPS	505074		505205	135184		1.00976E+12	ARV	3019656		505074	1	0	1	1	0		505074		505074						0				500111	1	PSI	3013729	MR	3019679	1	1010066					

VW:
48435720524	4295889557	3011624	SPG	1	48433350304	1	1000190358	1	1000190363	20011231	HalfYear	3011647	500111	0	ORG	3013560	NA	3019679	INC	3011683	36	14	ESPARS	3012178	SS	1000716240	D	3013563	2	2001	BEPSBC	3014780					1	97	Diluido	505205	Reported Basic EPS	505074			0.29029	0.30711	Reported Basic EPS	505074		505205	135184		20011231	ARV	3019656		505074	1	0	1	1	0		505074		505074				0		0				500111	1	PSI	3013729	MR	3019679	1	1010066

In [3]:
root_path = r'K:\Learn\ADC\phase3\hbasecompare\testing-data'
vw_file = root_path + '\\' + r'4295889557inc.csv'
hbase_file_head = root_path + '\\' + r'4295889557-INC-head50.csv'
hbase_file_head

'K:\\Learn\\ADC\\phase3\\hbasecompare\\testing-data\\4295889557-INC-head50.csv'

In [4]:
vw_data = pd.read_csv(vw_file, sep = '|')
hbase_data_head = pd.read_csv(hbase_file_head, sep = '|', header=None)
hbase_data_head.columns = vw_data.columns
hbase_data_head

K:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:2871: DtypeWarning: Columns (84,86) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,fundamentalid,organizationid,gaapcodeid,gaapcode,isusedforanalytics,fundamentalseriesid,fundamentalseriesviewtype,fundamentalseriesviewtypeid,fundamentalseriesconsolidationbasis,fundamentalseriesconsolidationbasisid,...,statementsectioncode,statementsectionid,systemderivedtypecode,systemderivedtypecodeid,unit,unitenumerationid,parentlineitemname,parentlineitemnamelanguageid,parentlinelocallanguagelabel,parentlinelocallanguagelabellanguageid
0,48435720520,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
1,48435720521,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1.0,1010066,nil,nil,nil,nil
2,48435720522,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,MR,3019679,1.0,1010066,nil,nil,nil,"nil,,,,,"
3,48435720523,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1.0,1010066,nil,nil,nil,"nil,,,,,"
4,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1.0,1010066,nil,nil,nil,"nil,,,,,"
5,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,REV,3013735,NaN,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
6,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,OEX,3013709,NaN,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
7,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,TAX,3013752,MR,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
8,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,REV,3013735,NaN,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
9,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,REV,3013735,NaN,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
10,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,OEX,3013709,NaN,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
11,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,REV,3013735,NaN,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
12,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,MR,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
13,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1.0,1010066,nil,nil,nil,"nil,,,,,"
14,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1.0,1010066,nil,nil,nil,"nil,,,,,"
15,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,REV,3013735,MR,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,"
16,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,OEX,3013709,MR,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
17,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PTX,3013731,MR,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
18,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,TAX,3013752,NaN,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
19,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,IAT,3019665,MR,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
20,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,NIN,3013702,MR,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
21,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,NIC,3019667,MR,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
22,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,NCN,3013697,MR,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
23,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,NCX,3013699,MR,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
24,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1.0,1010066,nil,nil,nil,nil
25,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,MR,3019679,1.0,1010066,nil,nil,nil,"nil,,,,,"
26,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1.0,1010066,nil,nil,nil,"nil,,,,,"
27,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
28,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
29,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1.0,1010066,nil,nil,nil,"nil,,,,,"
30,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,MR,3019679,1.0,1010066,nil,nil,nil,"nil,,,,,"
31,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1.0,1010066,nil,nil,nil,"nil,,,,,"
32,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1.0,1010066,nil,nil,nil,"nil,,,,,"
33,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,REV,3013735,NaN,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
34,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,OEX,3013709,NaN,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
35,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,TAX,3013752,MR,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
36,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,REV,3013735,NaN,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
37,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,REV,3013735,NaN,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
38,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,OEX,3013709,NaN,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
39,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,REV,3013735,NaN,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
40,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,MR,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,,"
41,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1.0,1010066,nil,nil,nil,"nil,,,,,"
42,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1.0,1010066,nil,nil,nil,"nil,,,,,"
43,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1.0,1010066,nil,nil,nil,"nil,,,,,"
44,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1.0,1010066,nil,nil,nil,"nil,,,,,"
45,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1.0,1010066,nil,nil,nil,"nil,,,,,"
46,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1.0,1010066,nil,nil,nil,"nil,,,,,"
47,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1.0,1010066,nil,nil,nil,"nil,,,,,"
48,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,PSI,3013729,NaN,3019679,1.0,1010066,nil,nil,nil,"nil,,,,,"
49,48435720524,4295889557,3011624,SPG,True,48433350304,OriginalToOriginal,1000190358,Blended,1000190363,...,REV,3013735,MR,3019679,1000.0,1010067,nil,nil,nil,"nil,,,,"

In [5]:
hbase_data_head.replace('nil', np.NAN, inplace=True)
hbase_data_head.replace(True, '1', inplace=True)
hbase_data_head.replace(False, '0', inplace=True)
hbase_data_head.replace('OriginalToOriginal', '1', inplace=True)
hbase_data_head.replace('RecentToRecent', '2', inplace=True)
hbase_data_head.replace('Blended', '1', inplace=True)
hbase_data_head.replace('ConsolidatedOnly', '2', inplace=True)
hbase_data_head
#hbase_data_head.to_csv(root_path + '\\' + r'test4295889557inc-head50.csv')
hbase_data_head

,fundamentalid,organizationid,gaapcodeid,gaapcode,isusedforanalytics,fundamentalseriesid,fundamentalseriesviewtype,fundamentalseriesviewtypeid,fundamentalseriesconsolidationbasis,fundamentalseriesconsolidationbasisid,...,statementsectioncode,statementsectionid,systemderivedtypecode,systemderivedtypecodeid,unit,unitenumerationid,parentlineitemname,parentlineitemnamelanguageid,parentlinelocallanguagelabel,parentlinelocallanguagelabellanguageid
0,48435720520,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
1,48435720521,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,NaN
2,48435720522,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,MR,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
3,48435720523,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
4,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
5,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,REV,3013735,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
6,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,OEX,3013709,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
7,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,TAX,3013752,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
8,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,REV,3013735,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
9,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,REV,3013735,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
10,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,OEX,3013709,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
11,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,REV,3013735,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
12,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
13,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
14,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
15,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,REV,3013735,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,"
16,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,OEX,3013709,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
17,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PTX,3013731,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
18,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,TAX,3013752,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
19,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,IAT,3019665,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
20,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,NIN,3013702,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
21,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,NIC,3019667,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
22,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,NCN,3013697,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
23,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,NCX,3013699,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
24,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,NaN
25,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,MR,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
26,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
27,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
28,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
29,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
30,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,MR,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
31,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
32,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
33,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,REV,3013735,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
34,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,OEX,3013709,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
35,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,TAX,3013752,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
36,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,REV,3013735,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
37,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,REV,3013735,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
38,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,OEX,3013709,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
39,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,REV,3013735,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
40,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
41,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
42,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
43,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
44,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
45,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
46,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
47,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
48,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
49,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,REV,3013735,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,"

In [6]:
#hbase_data_head.insert(0, 'md5', np.NAN, allow_duplicates=False)
#hbase_data_head.drop(['md5'], inplace=True, axis = 1, errors='ignore')
hbase_data_head

,fundamentalid,organizationid,gaapcodeid,gaapcode,isusedforanalytics,fundamentalseriesid,fundamentalseriesviewtype,fundamentalseriesviewtypeid,fundamentalseriesconsolidationbasis,fundamentalseriesconsolidationbasisid,...,statementsectioncode,statementsectionid,systemderivedtypecode,systemderivedtypecodeid,unit,unitenumerationid,parentlineitemname,parentlineitemnamelanguageid,parentlinelocallanguagelabel,parentlinelocallanguagelabellanguageid
0,48435720520,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
1,48435720521,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,NaN
2,48435720522,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,MR,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
3,48435720523,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
4,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
5,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,REV,3013735,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
6,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,OEX,3013709,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
7,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,TAX,3013752,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
8,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,REV,3013735,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
9,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,REV,3013735,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
10,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,OEX,3013709,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
11,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,REV,3013735,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
12,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
13,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
14,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
15,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,REV,3013735,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,"
16,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,OEX,3013709,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
17,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PTX,3013731,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
18,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,TAX,3013752,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
19,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,IAT,3019665,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
20,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,NIN,3013702,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
21,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,NIC,3019667,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
22,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,NCN,3013697,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
23,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,NCX,3013699,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
24,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,NaN
25,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,MR,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
26,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
27,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
28,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
29,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
30,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,MR,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
31,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
32,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
33,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,REV,3013735,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
34,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,OEX,3013709,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
35,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,TAX,3013752,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
36,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,REV,3013735,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
37,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,REV,3013735,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
38,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,OEX,3013709,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
39,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,REV,3013735,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
40,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
41,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
42,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
43,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
44,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
45,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
46,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
47,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
48,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
49,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,REV,3013735,MR,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,"

In [7]:
import hashlib
hbase_data_head.ix[:,1:]
tmp = hbase_data_head.ix[0,1:].to_string()
print tmp
#print tmp.to_string
#tmp
#hash1 = hashlib.md5("hello")
#print hash1.hexdigest()

organizationid                                    4295889557
gaapcodeid                                           3011624
gaapcode                                                 SPG
isusedforanalytics                                         1
fundamentalseriesid                              48433350304
fundamentalseriesviewtype                                  1
fundamentalseriesviewtypeid                       1000190358
fundamentalseriesconsolidationbasis                        1
fundamentalseriesconsolidationbasisid             1000190363
periodenddate                                  1009756800000
periodtype                                          HalfYear
periodtypeid                                         3011647
statementcurrencyid                                   500111
ispreliminary                                              0
updatetypecode                                           ORG
updatetypeid                                         3013560
statementsystemderivedtypecode                           NaN
statementsystemderivedtypecodeid                     3019679
statementtypecode                                        INC
statementtypecodeid                                  3011683
financialperiodid                                         36
financialsourceid                                         14
sourcetypecode                                        ESPARS
sourcetypeid                                         3012178
thirdpartysourcecode                                      SS
thirdpartysourcecodeid                            1000716240
cumulativetype                                             D
cumulativetypeid                                     3013563
interimnumber                                            NaN
interimperiodfiscalyear                                  NaN
financialconceptglobal                                  CDNI
financialconceptglobalid                             3018735
financialconceptcodeglobalsecondary                      NaN
financialconceptcodeglobalsecondaryid                    NaN
financialconceptlocal                                    NaN
financialconceptlocalid                                  NaN
asriscredit                                                1
lineitemlineitemid                                       100
locallanguagelabel                                       NaN
locallanguagelabellanguageid                          505074
lineitemname                              Diluted Net Income
lineitemnamelanguageid                                505205
physicalmeasureid                                        NaN
orglineitemsequence                                      NaN
asradjustedforcorporateactionvalue                       NaN
lineitemvalue                                      2.752e+06
asreportedlineitemname                    Diluted Net Income
asreportedlineitemnamelanguageid                      505074
lineitemlocallanguagelabel                Diluted Net Income
lineitemlocallanguagelabellanguageid                  505205
asrlineitemsequence                                   147472
asreportedlineitemsource                                 NaN
capitalchangeadjustmentdate                              NaN
estimatemethodcode                                       ARV
estimatemethodid                                     3019656
estimatemethodnote                                       NaN
estimatemethodnotelanguageid                          505074
isasreportedcurrencysetmanually                            0
iscombineditem                                             0
isderived                                                  0
isfinal                                                    1
istotal                                                    0
editeddescription                                        NaN
editeddescriptionlanguageid                           505074
reporteddescription                                      NaN
reporteddescriptionlanguageid                         505074
bookmark                                                 NaN
docbytelength                                            NaN
docbyteoffset                                            NaN
itemdisplayednegativeflag                                NaN
itemdisplayedvalue                                       NaN
itemscalingfactor                                          3
reportedvalue                                            NaN
parentlineitemid                                         NaN
asreportedphysicalmeasureid                              NaN
reportedcurrencyid                                    500111
statementsectioniscredit                                   1
statementsectioncode                                     PSI
statementsectionid                                   3013729
systemderivedtypecode                                    NaN
systemderivedtypecodeid                              3019679
unit                                                    1000
unitenumerationid                                    1010067
parentlineitemname                                       NaN
parentlineitemnamelanguageid                             NaN
parentlinelocallanguagelabel                             NaN
parentlinelocallanguagelabellanguageid              nil,,,,,

In [8]:
hbase_data1 = pd.read_fwf(hbase_file_head, header = None)
print hbase_data1[0:1].to_string()
data_tmp = hbase_data1[0:4]
print data_tmp
data_string = data_tmp.to_string()
print hashlib.md5(data_string).hexdigest()
data_tmp.to_csv('hello.txt', index=False)

                                                   0
0  48435720520|4295889557|3011624|SPG|True|484333...
                                                   0
0  48435720520|4295889557|3011624|SPG|True|484333...
1  48435720521|4295889557|3011624|SPG|True|484333...
2  48435720522|4295889557|3011624|SPG|True|484333...
3  48435720523|4295889557|3011624|SPG|True|484333...
ba1c70b0bbe333506d761e3f9ddd3cd7

In [9]:
def hashmd5code(str):
    return hashlib.md5(str).hexdigest()

In [10]:
#data_tmp.insert(0, 'md5', np.NAN, allow_duplicates=False)
print data_tmp
print '----------------'
#print hashlib.md5(data_tmp.ix[2, 0]).hexdigest()
#data_tmp1 =data_tmp.ix[:,1]
data_tmp.md5 = data_tmp.ix[:,1].apply(hashmd5code)

#hcode_tmp = data_tmp1.apply(hashmd5code)
#hcode_tmp
#data_tmp.md5 = hcode_tmp
print data_tmp
#data_tmp['md5'] = hashlib.md5(data_tmp[0]).hexdigest()

                                                   0
0  48435720520|4295889557|3011624|SPG|True|484333...
1  48435720521|4295889557|3011624|SPG|True|484333...
2  48435720522|4295889557|3011624|SPG|True|484333...
3  48435720523|4295889557|3011624|SPG|True|484333...
----------------

KeyError: 1L

In [ ]:
part0_file = root_path + '\\' + r'part-00000.csv'
part0_data = pd.read_csv(part0_file, header=None, delimiter='\n', names=['valstring'])
part0_data.head()

In [11]:
part0_data.insert(0, 'md5', np.NAN, allow_duplicates=False)

NameError: name 'part0_data' is not defined

In [253]:
part0_data.md5 = part0_data.ix[:,'valstring'].apply(hashmd5code)
part0_data.head()

,md5,valstring
0,f4c2cd0d0502be6b1a66f779f8f5ee81,48435944139|4295882444|3011566|IAS|True|484333...
1,a19c62f9efda3d106c08f6944cbcb971,48435944139|4295882444|3011566|IAS|True|484333...
2,490b0291aed1830179a0533a29b70032,48435944139|4295882444|3011566|IAS|True|484333...
3,c9b721b362e3da3af05795bd76b43dd0,48435944139|4295882444|3011566|IAS|True|484333...
4,a74cdfce07847452d6884d9df0c18bf4,48435944139|4295882444|3011566|IAS|True|484333...

In [254]:
part0_data.sort_values('md5')

,md5,valstring
284149,0000075f2eee868519dd321c92e4fc19,48435895927|4295882680|3011566|IAS|True|484333...
333299,000008c2faf77b63c7fe5457b32dc6b9,48435924954|4295882670|3011566|IAS|True|484332...
142220,00001d6de3715622e3c4d195d38f57a7,48435903834|4295881207|3011566|IAS|True|484332...
1243942,00001e8a50d2058e06d6064262d72ee9,48435944154|4295882444|3011579|KOG|True|484332...
1370576,000024911583b0c776eeee3aa3b34e2c,48434108978|4295872696|3011568|IDG|False|48433...
521631,0000310a9950caa864340e6a589b1406,48433430250|4295880164|3011577|JPG|True|484331...
426972,000034ad72974cd34a7bb2669f44904b,48436045031|4295860511|3011566|IAS|True|484332...
1520779,000034cf75547b51ec91f1253010c28d,48436049868|4295860592|3011566|IAS|True|484331...
16379,000035514adb2b699a6d6ce0bb89bf31,48435658579|4295913317|3011639|USG|True|484331...
1169820,0000392ee05a7e72bbe33a056c0d8169,48434381255|4295904315|3011639|USG|False|48433...
265115,00004d192241eef2b301046a1a78b90a,48435905405|4295881759|3011579|KOG|True|484333...
832716,00004e2c0685949b533f54300f1fb051,48435831884|8589934312|3011566|IAS|True|484331...
1195194,00005ee661cf33e3ce4b518569d3e6e3,48433958002|4298149896|3011537|CHG|True|484332...
1133651,00006de3cebd8862fa901635aea646ca,48435892503|4295881398|3011566|IAS|True|484332...
804701,00007052be12ef95b6a67827147de068,48436132872|4295881819|3011579|KOG|True|484333...
798839,0000756bf9d32326fc1960d2a7f04a8c,48435588830|4295859753|3011532|BRG|True|484331...
360031,00007cbf4035909d999942d061ddff15,48433417879|4295881123|3011579|KOG|True|484331...
1495457,000084e0d737adf414b6f4e7a8bcd320,48434662901|4297561053|3011641|VTG|True|484333...
250210,00008acfda05f81d2266460adfca6dc8,48435658579|4295913317|3011639|USG|True|484331...
1035773,0000a9fe762806c0f55982457ec8bdac,48433416793|4295860511|3011536|CAG|True|484332...
1260556,0000b00fcdb3cda530e226b0da8f293e,48434098578|4295869694|3011566|IAS|True|484331...
1798931,0000c0613a5def45d524b0bbb08cda9c,48435892537|4295881398|3011579|KOG|True|484332...
1466153,0000c2c73ecfb0bb1e2ab8ee95b31d53,48433430360|4295878300|3011577|JPG|True|484331...
1526730,0000c405a0eaf48bd37b85f555c4e3c2,48433417879|4295881123|3011579|KOG|True|484331...
1085802,0000d34bb640ea4bb798bbeccd62f251,48434098578|4295869694|3011566|IAS|True|484331...
1684074,0000d48c2711b5e5ceb2f65275f77159,48434098578|4295869694|3011566|IAS|True|484331...
359284,0000dad9cc7cd37988fb72c4d4b0aa0a,48434098578|4295869694|3011566|IAS|True|484331...
1739783,0000ee8fbce2348b9a5ebc114743d1ac,48435892503|4295881398|3011566|IAS|True|484332...
1604830,0000f521d21e70f80e008f22c9eaa403,48434098577|4295869694|3011639|USG|True|484331...
1011912,000102a386b630a4f083ebb6c987fc89,48435944154|4295882444|3011579|KOG|True|484332...
...,...,...
1497804,ffff065fab2cb1fd6b14dd0dd832bfad,48435831884|8589934312|3011566|IAS|False|48433...
561055,ffff1cd46f813f27a3bb508bef75c020,48435924956|4295882670|3011579|KOG|True|484332...
1258545,ffff1fb99bc134cd19ed1cc7504b9e22,48434118199|4295887273|3011566|IAS|True|484333...
1078040,ffff29b5909ddb8a542d5484274c92a7,48433430249|4295880164|3011577|JPG|True|484331...
929428,ffff36d361a381563a6aedcf06d97b26,48436052730|4295864209|3011537|CHG|True|484332...
882407,ffff3d28e50562f419782dcb20f611cd,48434098577|4295869694|3011639|USG|True|484331...
700055,ffff4bc6ab3d2beed9219ddb57163f6f,48433416793|4295860511|3011536|CAG|True|484332...
589696,ffff50d7be04dbf331e359996fd80055,48435944139|4295882444|3011566|IAS|True|484333...
1215983,ffff557893d12030bffbfcae4d000b79,48435944364|4295882444|3011579|KOG|True|484332...
1636449,ffff58f53512c1c02d2ab015a68dfb14,48433430250|4295880164|3011577|JPG|True|484331...
1600298,ffff5b6340e788c79930bf8b02560311,48435892954|4295882112|3011579|KOG|True|484331...
1737423,ffff5f16f403a968df987e84914657bc,48435957367|4295891852|3011566|IAS|True|484332...
927429,ffff786b64ce6762a322df6d89e84d0f,48433430250|4295880164|3011577|JPG|True|484331...
141259,ffff854dd233b49f0e6ee5183e40244d,48436034885|4295861241|3011536|CAG|True|484331...
427927,ffff8f94bec37aa4ed135cee29896f18,48435480564|4295893235|3011629|THG|True|484332...
1113784,ffff96de920204ddeaa89d533cc544d3,48435903834|4295881207|3011566|IAS|True|484333...
868918,ffff9c0b952a1da6b61edebdd027d69d,48435892841|4295882112|3011566|IAS|True|484331...
251430,ffff9f4ea5c447e5fa6dae0f01e3ae88,48435944364|4295882444|3011579|KOG|True|484332...
1384056,ffffaf171706a94f79b14a046c1f748e,48435903981|4295881207|3011579|KOG|True|484332...
1187453,ffffbe53322e762aac841b4f566c5ceb,48433597689|4295878300|3011577|JPG|True|484331...
1021972,ffffbf3c24cfc3e5f7af5eae4fc387e4,48436041072|4295864381|3011537|CHG|True|484333...
1060149,ffffcc7d5d7a4391f925c47c4a52ca1c,48434381255|4295904315|3011639|USG|True|484331...
1607259,ffffd06bd6b419c8e2aff212b3f7cc89,48436052730|4295864209|3011537|CHG|True|484332...
1758571,ffffd29af88bf4b44cf42fe358a63dc3,48434662901|4297561053|3011641|VTG|True|484333...
1190854,ffffd66c9afa34841f7e28882945bcc1,48435892954|4295882112|3011579|KOG|True|484331...
1726360,ffffe6804927fd25b9b8f494e1b06dd5,48435905293|4295881759|3011566|IAS|True|484331...
626996,fffff0db72379bac7bac5071490767dc,48436124641|4295882445|3011579|KOG|True|484331...
23571,fffff56a3bee4c5d336fca03f05a1cee,48435588760|4295859753|3011566|IAS|True|484331...
285846,fffff88e6e7105f4a5db3e15b1120c5e,48435903981|4295881207|3011579|KOG|True|484332...
921786,ffffffd455dd420816575e4c5e80e342,48435944139|4295882444|3011566|IAS|True|484332...

# use rowkey_logicalfield

In [12]:
hbase_data_head.head()

,fundamentalid,organizationid,gaapcodeid,gaapcode,isusedforanalytics,fundamentalseriesid,fundamentalseriesviewtype,fundamentalseriesviewtypeid,fundamentalseriesconsolidationbasis,fundamentalseriesconsolidationbasisid,...,statementsectioncode,statementsectionid,systemderivedtypecode,systemderivedtypecodeid,unit,unitenumerationid,parentlineitemname,parentlineitemnamelanguageid,parentlinelocallanguagelabel,parentlinelocallanguagelabellanguageid
0,48435720520,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
1,48435720521,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,NaN
2,48435720522,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,MR,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
3,48435720523,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
4,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,1000190363,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"

In [13]:
hbase_data_head.insert(0, 'rowkeylogicalfield', np.NAN, allow_duplicates=False)

In [19]:
rowkey_logicalfield_fields = ['fundamentalseriesid', 'statementtypecode' ,'financialconceptlocalid', 'periodenddate', 'financialsourceid', 'financialperiodid', 'lineitemlineitemid']

hbase_data_head.rowkeylogicalfield = hbase_data_head['fundamentalseriesid'].to_string() + '~' + hbase_data_head['statementtypecode']
hbase_data_head.head()

,rowkeylogicalfield,fundamentalid,organizationid,gaapcodeid,gaapcode,isusedforanalytics,fundamentalseriesid,fundamentalseriesviewtype,fundamentalseriesviewtypeid,fundamentalseriesconsolidationbasis,...,statementsectioncode,statementsectionid,systemderivedtypecode,systemderivedtypecodeid,unit,unitenumerationid,parentlineitemname,parentlineitemnamelanguageid,parentlinelocallanguagelabel,parentlinelocallanguagelabellanguageid
0,0 48433350304\n1 48433350304\n2 48...,48435720520,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,...,PSI,3013729,NaN,3019679,1000,1010067,NaN,NaN,NaN,"nil,,,,,"
1,0 48433350304\n1 48433350304\n2 48...,48435720521,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,NaN
2,0 48433350304\n1 48433350304\n2 48...,48435720522,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,...,PSI,3013729,MR,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
3,0 48433350304\n1 48433350304\n2 48...,48435720523,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"
4,0 48433350304\n1 48433350304\n2 48...,48435720524,4295889557,3011624,SPG,1,48433350304,1,1000190358,1,...,PSI,3013729,NaN,3019679,1,1010066,NaN,NaN,NaN,"nil,,,,,"