In [39]:
import tushare as ts
import numpy as np
import pandas as pd
import h5py
import urllib2

In [2]:
d = ts.get_tick_data('600848',date='2015-01-09')

In [8]:
len(d)
h5.close()
h5 = pd.HDFStore('./data/test2.h5','w')
h5['data'] = d
h5.close()

In [10]:
h5 = pd.HDFStore('./data/test2.h5','r')
e = h5['data']
h5.close()

In [26]:
f = h5py.File('./data/test2.h5', 'r')
f

In [27]:
f2017 = pd.read_excel('./data/frameleftT1-2017.xlsx')
f2017

,opendate,name,h1,h2,h3,h4,h5,h6,h7,h8,...,13/1/2017,2017-12-01 00:00:00,2017-11-01 00:00:00,2017-10-01 00:00:00,2017-09-01 00:00:00,2017-06-01 00:00:00,2017-05-01 00:00:00,2017-04-01 00:00:00,2017-03-01 00:00:00,Unnamed: 23
0,sh600000,浦发银行,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3602.008672,-704.657868,5.075518,-858.750720,-1564.43,-3209.523190,2879.466155,-463.096461,652.806110,-858.750720
1,sh600001,邯郸钢铁,--,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000
2,sh600003,ST东北高,--,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000
3,sh600004,白云机场,-12.76,-2.2,-1.06,-3.71,-12.3,-10.31,0.26,--,...,22.274830,-200.990287,-269.969045,0.000000,509.83,115.200000,-506.741800,940.724854,-260.617400,0.000000
4,sh600005,武钢股份,-2.64,-2.11,-12.5,-2.12,24.24,-4.54,-8.15,--,...,1158.115290,-57.520017,867.470843,353.863869,-52.1761,754.710733,1440.782578,905.203249,419.888700,353.863869
5,sh600006,东风汽车,-3.54,-15.58,-1.03,-9.83,18.15,31.45,2.74,--,...,-923.889268,-538.973236,-100.557572,-766.773000,-135.418,1198.092576,-327.897795,168.183766,-362.082400,-766.773000
6,sh600007,中国国贸,-10.25,-18.72,-0.92,-0.14,-16.62,-22.86,14.24,4.95,...,716.894000,0.000000,431.127490,1317.872420,172.088,908.206000,-123.886260,45.238800,108.812500,1317.872420
7,sh600008,首创股份,9.06,1.54,-0.69,5.58,1.87,-11.2,-7.01,0.28,...,1343.248680,-629.599820,-1134.666672,-775.370000,-196.842,1188.637300,-514.091435,215.956600,-142.154600,-775.370000
8,sh600009,上海机场,-15.55,13.01,-3.06,-4.7,-7.29,-23.68,21.98,-7.01,...,-1621.210380,-117.731360,-378.337300,-770.798956,-46.2568,-842.020100,61.432600,-419.011296,213.226200,-770.798956
9,sh600010,包钢股份,-2.25,-3.65,-0.24,-11.52,-17.47,36.44,17.43,-5.68,...,1181.725234,-2744.478386,1046.804553,2784.679957,289.122,1435.421840,1517.891993,-3100.225734,2463.190844,2784.679957
10,sh600011,华能国际,-32.45,32.38,8.41,--,NaN,NaN,NaN,NaN,...,2933.654498,-694.133510,933.705749,402.276244,492.699,2432.544543,-1073.677824,-896.721235,320.895336,402.276244
11,sh600012,皖通高速,--,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,992.416000,-1065.369500,-8883.059842,-1566.316032,-475.076,97.793192,428.497678,143.204500,-296.768000,-1566.316032
12,sh600015,华夏银行,1.82,-1.05,-1.36,-6.72,-24.13,13.98,-4.23,3.54,...,2638.125514,345.013233,-4020.327462,45.341699,1612.85,-2543.162279,-2066.511278,891.080115,4414.706801,45.341699
13,sh600016,民生银行,--,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3018.996034,-1065.401964,-298.466574,-802.979086,6043.25,-2745.993040,-1958.538489,-6684.892744,1054.110359,-802.979086
14,sh600017,日照港,-5.32,-5.71,3.89,-3.9,-13.38,41.72,19.4,--,...,-1048.190296,-898.535288,-222.277364,3621.221455,-501.264,101.675510,-607.833768,4945.967100,5872.754802,3621.221455
15,sh600018,上港集团,-2.78,-7.83,1.13,-0.58,-6.01,-22.78,30.63,7.06,...,828.601120,1649.576600,-276.812100,-182.752200,-467.587,-926.834850,943.329899,1705.418362,948.151842,-182.752200
16,sh600019,宝钢股份,0.02,-1.82,-1.13,-4.23,-10.58,-4.5,-8.35,1.39,...,667.118791,-371.875073,-2038.864409,4393.364876,2919.47,3434.647605,672.174036,-82.113745,1789.557668,4393.364876
17,sh600020,中原高速,-3.9,0.97,-3.11,-12.43,4.03,-24.64,21.9,26.57,...,-290.424585,118.097535,-1184.871730,800.225000,402.728,589.299194,284.232258,454.979739,841.912392,800.225000
18,sh600021,上海电力,0.04,-5.06,-3.4,-5.22,6.69,-9.19,-16.2,40.51,...,510.241397,-251.488850,-1107.157479,-1008.853614,125.163,3767.190773,-666.405260,-299.811000,-85.147000,-1008.853614
19,sh600022,山东钢铁,-2.14,-5.23,-1.23,-21.48,5.52,29.19,-3.61,11.54,...,154.116210,-3911.006048,2500.883194,2425.597700,-3733.42,1162.675276,-695.910095,1307.912399,435.298925,2425.597700
20,sh600023,浙能电力,-6.18,-2.13,-1.94,-12.21,-31.02,474.54,-0.01,5.09,...,-186.266640,-711.520500,-730.688694,-2298.341307,6728.2,-4470.377535,6816.919590,345.647031,1007.782566,-2298.341307
21,sh600026,中远海能,-9.18,18.35,-29.58,--,NaN,NaN,NaN,NaN,...,1303.655420,-1236.926848,-1036.486919,749.450824,-112.855,1386.933158,163.789616,659.006139,493.766400,749.450824
22,sh600027,华电国际,--,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-45.045370,-1084.321622,666.466330,-1601.240848,919.548,1759.871345,-878.756151,-409.491470,-52.373600,-1601.240848
23,sh600028,中国石化,-6.2,-5.35,-11.96,-7.33,10.46,--,NaN,NaN,...,4680.218194,-1255.191727,-5488.670601,-5155.663796,-1073.54,2054.653182,17291.515025,4067.144044,9160.868536,-5155.663796
24,sh600029,南方航空,--,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,656.344271,-4068.222536,-23580.106270,88878.908288,-232.174,-2259.924943,-2287.516417,2626.998126,960.385941,88878.908288
25,sh600030,中信证券,-3.54,-5.06,-1.9,0.56,-1.65,-9.62,--,NaN,...,17303.934208,1231.796624,625.283895,-2934.664518,-5085.32,-10402.141498,-6132.043497,-2972.797133,2269.059388,-2934.664518
26,sh600031,三一重工,-6.83,-2.28,-2.74,-10.46,-7.4,1.77,3.23,17.41,...,-575.529289,-298.539033,-2208.133412,-544.700980,753.163,-700.289780,5373.426166,1387.371848,1472.049508,-544.700980
27,sh600033,福建高速,-5.74,-4.04,-4.41,-9.63,3.06,16.25,-3.83,16.36,...,0.000000,-241.664096,-767.710928,591.227210,-345.11,-108.724000,-16.889500,314.755600,-440.078294,591.227210
28,sh600035,楚天高速,-3.65,0.33,-2.31,-13.85,-9.6,97.41,5.83,22.98,...,183.163100,658.620000,-111.240000,367.200000,660.239,-382.632000,564.917774,112.664200,-136.842300,367.200000
29,sh600036,招商银行,6.1,--,NaN,NaN,NaN,NaN,NaN,NaN,...,7578.528894,-131.003174,-1996.589028,-702.198594,-427.238,-2752.943660,4832.798291,4849.051506,2673.848525,-702.198594
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3072,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
3073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,253.973,NaN,NaN,NaN,NaN,NaN
3074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-136.407,NaN,NaN,NaN,NaN,NaN
3075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,411.122,NaN,NaN,NaN,NaN,NaN
3076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-823.057,NaN,NaN,NaN,NaN,NaN
3077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,79.2025,NaN,NaN,NaN,NaN,NaN
3078,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
3079,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
3080,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,103.936,NaN,NaN,NaN,NaN,NaN
3081,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
3082,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
3083,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
3084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
3085,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
3086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-2019.9,NaN,NaN,NaN,NaN,NaN
3087,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
3088,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-268.951,NaN,NaN,NaN,NaN,NaN
3089,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-107.873,NaN,NaN,NaN,NaN,NaN
3090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
3091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,746.198,NaN,NaN,NaN,NaN,NaN
3092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-127.56,NaN,NaN,NaN,NaN,NaN
3093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,60.7175,NaN,NaN,NaN,NaN,NaN
3094,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-60.6133,NaN,NaN,NaN,NaN,NaN
3095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,412.365,NaN,NaN,NaN,NaN,NaN
3096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,274.232,NaN,NaN,NaN,NaN,NaN
3097,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-414.346,NaN,NaN,NaN,NaN,NaN
3098,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-124.608,NaN,NaN,NaN,NaN,NaN
3099,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,203.768,NaN,NaN,NaN,NaN,NaN
3100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,36.0423,NaN,NaN,NaN,NaN,NaN
3101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1417.54,NaN,NaN,NaN,NaN,NaN

In [35]:
h52017 = pd.HDFStore('./data/f2017a.h5', 'w')
h52017['data'] = f2017
h52017.close()

K:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:2: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->axis0] [items->None]

  from IPython.kernel.zmq import kernelapp as app
K:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:2: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block0_items] [items->None]

  from IPython.kernel.zmq import kernelapp as app
K:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3035: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed-integer,key->block1_values] [items->[u'opendate', u'name', u'h1', u'h2', u'h3', u'h4', u'h5', u'h6', u'h7', u'h8', u'h9', u'h10', u'hjcg', datetime.datetime(2017, 9, 1, 0, 0)]]

  exec(code_obj, self.user_global_ns, self.user_ns)
K:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:2: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block1_items] [items->None]

  from IPython.kernel.zmq import kernelapp as app

In [36]:
h5 = pd.HDFStore('./data/f2017a.h5','r')
e = h5['data']
h5.close()

In [71]:
url = r'http://table.finance.yahoo.com/table.csv?s=600099.ss&b=1'
frameresult = pd.read_csv(url)
frameresult

            Date      Open      High       Low     Close    Volume  Adj Close
0     2017-01-13  17.98000  18.74000  17.85000  17.94000  13991600   17.94000
1     2017-01-12  17.91000  18.46000  17.70000  17.84000  16371100   17.84000
2     2017-01-11  18.72000  18.82000  17.52000  17.68000  19666300   17.68000
3     2017-01-10  18.90000  19.47000  18.52000  19.12000  20335800   19.12000
4     2017-01-09  18.73000  19.60000  18.23000  18.99000  23383700   18.99000
5     2017-01-06  19.29000  20.08000  18.18000  19.03000  25896000   19.03000
6     2017-01-05  19.60000  19.90000  18.90000  19.52000  29013400   19.52000
7     2017-01-04  20.86000  21.02000  18.74000  19.95000  51296100   19.95000
8     2017-01-03  18.99000  20.82000  18.85000  20.82000  41564800   20.82000
9     2017-01-02  18.93000  18.93000  18.93000  18.93000         0   18.93000
10    2016-12-30  19.70000  20.67000  18.80000  18.93000  35981200   18.93000
11    2016-12-29  19.53000  21.00000  19.28000  20.14000  38486600   20.14000
12    2016-12-28  21.00000  21.57000  19.48000  19.99000  47664800   19.99000
13    2016-12-27  18.32000  19.61000  17.60000  19.61000  29412600   19.61000
14    2016-12-26  16.00000  17.83000  15.84000  17.83000  34764400   17.83000
15    2016-12-23  14.50000  16.21000  14.48000  16.21000  34862300   16.21000
16    2016-12-22  14.65000  14.89000  14.33000  14.74000  14782800   14.74000
17    2016-12-21  15.25000  15.30000  14.43000  14.86000  27580700   14.86000
18    2016-12-20  13.38000  14.77000  13.20000  14.77000  17851400   14.77000
19    2016-12-19  13.22000  13.49000  13.11000  13.43000   4835200   13.43000
20    2016-12-16  12.76000  13.45000  12.75000  13.31000   6260800   13.31000
21    2016-12-15  12.80000  12.96000  12.55000  12.81000   4339300   12.81000
22    2016-12-14  12.56000  12.93000  12.45000  12.62000   4505100   12.62000
23    2016-12-13  12.34000  12.59000  12.16000  12.53000   3510800   12.53000
24    2016-12-12  13.32000  13.39000  12.33000  12.35000   5734500   12.35000
25    2016-12-09  13.47000  13.47000  13.27000  13.30000   3604200   13.30000
26    2016-12-08  13.50000  13.64000  13.34000  13.47000   4925500   13.47000
27    2016-12-07  13.33000  13.53000  13.25000  13.45000   3832600   13.45000
28    2016-12-06  13.15000  13.51000  13.15000  13.37000   4243900   13.37000
29    2016-12-05  13.02000  13.32000  13.00000  13.09000   3227000   13.09000
...          ...       ...       ...       ...       ...       ...        ...
5026  1997-08-14  11.60001  12.29000  11.60001  12.27999   1134900    6.10106
5027  1997-08-13  12.01000  12.38001  11.49999  11.52000   1289900    5.72347
5028  1997-08-12  12.27999  12.50001  12.05000  12.08999   1143500    6.00666
5029  1997-08-11  13.04999  13.09000  12.25000  12.27999   2771000    6.10106
5030  1997-08-08  13.40001  13.45000  12.99999  13.02000   1699200    6.46872
5031  1997-08-07  13.04999  13.34001  12.90000  13.31000   1543900    6.61280
5032  1997-08-06  13.31000  13.34999  13.05999  13.17999   1582000    6.54821
5033  1997-08-05  13.62000  13.68000  13.32000  13.40001    955300    6.65752
5034  1997-08-04  13.28001  13.75000  13.28001  13.55000   1618500    6.73204
5035  1997-08-01  13.33000  13.52999  13.20000  13.45000   1079700    6.68236
5036  1997-07-31  13.46999  13.58001  13.11999  13.38000   1599000    6.64758
5037  1997-07-30  13.10001  13.46999  13.02000  13.40001   1541200    6.65752
5038  1997-07-29  12.89000  13.20000  12.69999  12.99999   2009800    6.45878
5039  1997-07-28  13.50000  13.59999  12.80001  12.95000   1630800    6.43394
5040  1997-07-25  13.29999  13.68000  13.21000  13.50000   2594400    6.70720
5041  1997-07-24  13.38000  13.75000  13.29999  13.40001   2545000    6.65752
5042  1997-07-23  13.95999  14.15000  13.29999  13.39000   4148100    6.65255
5043  1997-07-22  13.73000  14.09000  13.10999  13.81000   5195100    6.86122
5044  1997-07-21  14.40000  14.40000  13.70001  13.82999   5670600    6.87115
5045  1997-07-18  14.84999  14.88000  14.30999  14.48999   4628800    7.19905
5046  1997-07-17  14.63000  14.88000  14.45000  14.83000   6721200    7.36798
5047  1997-07-16  14.16000  15.00000  13.92000  14.67999   8956800    7.29345
5048  1997-07-15  14.30001  14.48001  13.71999  14.16000   8003500    7.03510
5049  1997-07-14  14.40000  14.77000  14.00001  14.31999  15016300    7.11459
5050  1997-07-11  12.86999  14.07999  12.74999  14.05000  13735100    6.98045
5051  1997-07-10  13.25000  13.45000  12.89000  12.92001   8208800    6.41904
5052  1997-07-09  13.45000  13.58999  12.80001  13.15000  10868300    6.53331
5053  1997-07-08  12.74999  13.81000  12.61000  13.45000  18113400    6.68236
5054  1997-07-07  12.73000  13.34999  12.30000  12.55000  25159100    6.23521
5055  1997-07-04  11.79999  13.37000  11.78001  12.44999  53151500    6.18552

[5056 rows x 7 columns]

In [62]:
url1 = r'http://vip.stock.finance.sina.com.cn/quotes_service/api/json_v2.php/MoneyFlow.ssl_bkzj_ssggzj?page=1&num=20&sort=r0_net&asc=0&bankuai=&shichang='
frameresult1 = pd.read_json(url)
frameresult1

ValueError: Expected object or value

In [69]:
import ystockquote
print ystockquote.get_price('GOOG')

807.88